"""add wallet transaction ledger

Revision ID: ac01e5ad0ed6
Revises: 64adaf280cb3
Create Date: 2026-09-28 11:21:43.873859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac01e5ad0ed6'
down_revision: Union[str, Sequence[str], None] = '64adaf280cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_wallets_balance_kobo_nonnegative",
        "wallets",
        "balance_kobo >= 0",
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("transaction_type", sa.String(length=6), nullable=False),
        sa.Column("amount_kobo", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transaction_type IN ('credit', 'debit')",
            name="ck_transactions_transaction_type_valid",
        ),
        sa.CheckConstraint(
            "amount_kobo > 0",
            name="ck_transactions_amount_kobo_positive",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_wallet_id"),
        "transactions",
        ["wallet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transactions_wallet_id"),
        table_name="transactions",
    )
    op.drop_table("transactions")
    op.drop_constraint(
        "ck_wallets_balance_kobo_nonnegative",
        "wallets",
        type_="check",
    )
    # ### end Alembic commands ###
